#!/usr/bin/env lua

Stubs = require 'lua/stubs'
Lexer = require 'lua/lexer'
Skeleton = require 'lua/skeleton'

string_reader = Stubs.string_reader
parse_skeleton = Skeleton.parse_skeleton

while true do
  io.stdout:write('> ')
  local input = io.stdin:read()

  if not input then break end

  print(Skeleton.inspect(parse_skeleton(Lexer.new(string_reader(input)))))
end
